<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Post>
 */
class PostFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            // The title of the post is a single sentence, generated by the faker.
            // This is a quick way to generate a random title for a post.
            'title' => $this->faker->sentence(),
            // The content of the post is a paragraph, generated by the faker.
            // This is a quick way to generate a random content for a post.
            'content' => $this->faker->paragraph(),
            'user_id' => $this->faker->numberBetween(1, 10),
        ];
    }
}
